[package]
name = "learn_usb_protocal"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.40.0", features = ["full"] }
usbip = "0.7.1"
